### ISSUE TITLE
Tracking Issue GLVF 1.0 Team Long Long Dragon

### ISSUE THREAD

**Issue by Deecellar** [LongLongDragonTeam/GLVF#1]
## API Progress

- [x] Core API
- [x] Controllable State
- [x] Controllable Size
- [x] Controllable UI
- [x] Controllable Title
- [x] Enhanced Debugging
- [x] Event Driven Pump
- [x] File Drop
- [x] Gamepad Input
- [x] Joystick Input
- [x] Keyboard Input
- [x] Mouse Input
- [x] Multiview Support
- [x] OpenGL support
- [x] Vulkan support
- [ ] Screen APIs
## Development
- [ ] [In Progress]  GLVF emulation on desktop via GLFW
- [ ] [Not Started] iOS support
- [ ] [Not Started] Android support
## Milestones
 - [ ] Preview 1 with Android Support
 - [ ] Preview 2 with iOS support
 - [ ] Preview 3 with Desktop support
 - [ ] Preview 4 bugfix and release candidate
 - [ ] Full release version 1.0
